<Project Sdk="Microsoft.NET.Sdk.Web">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <UserSecretsId>ad5d0eeb-a279-4804-a474-66a885453fc3</UserSecretsId>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\ChannelsService.Application\ChannelsService.Application.csproj" />
      <ProjectReference Include="..\ChannelsService.External\ChannelsService.External.csproj" />
      <ProjectReference Include="..\ChannelsService.Outbox\ChannelsService.Outbox.csproj" />
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="10.0.2" />
        <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.3"/>
    </ItemGroup>

</Project>
